// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swivaiakgzzzwdumnbam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3aXZhaWFrZ3p6endkdW1uYmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDM4OTksImV4cCI6MjA2NDE3OTg5OX0.PzLxdl1spnEosej2XNiJQnQ2rxOv4VT5TF5xcU6ms7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);